In [1]:
!nvidia-smi

Sat Jan  7 14:39:59 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 516.94       Driver Version: 516.94       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:06:00.0  On |                  N/A |
| 24%   25C    P8    N/A /  75W |    184MiB /  4096MiB |      7%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch
torch.__version__

'1.8.2+cu111'

## Introduction to Tensors

### Creating Tensors

Pytorch Tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Pytrhon int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([[7,8],
                        [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors = https://pytorch.org/docs/stable/generated/torch.rand.html

In [18]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9221, 0.8643, 0.1040, 0.5042],
        [0.5895, 0.0167, 0.8290, 0.3396],
        [0.9548, 0.2033, 0.3134, 0.3119]])

In [19]:
random_tensor.ndim

2

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, colour channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
random_image_size_tensor

tensor([[[0.8282, 0.7274, 0.3992],
         [0.9642, 0.6629, 0.4343],
         [0.3533, 0.7511, 0.5781],
         ...,
         [0.3607, 0.7882, 0.6545],
         [0.3494, 0.8577, 0.4499],
         [0.1415, 0.3153, 0.9371]],

        [[0.0481, 0.7868, 0.1207],
         [0.3445, 0.8992, 0.2328],
         [0.5521, 0.1364, 0.2071],
         ...,
         [0.5319, 0.4910, 0.9098],
         [0.6257, 0.0116, 0.9793],
         [0.1618, 0.0120, 0.0460]],

        [[0.8699, 0.2433, 0.2652],
         [0.4996, 0.5022, 0.0862],
         [0.7255, 0.0077, 0.7364],
         ...,
         [0.9307, 0.7340, 0.4701],
         [0.0118, 0.6645, 0.9371],
         [0.3436, 0.5528, 0.8403]],

        ...,

        [[0.4937, 0.3620, 0.8599],
         [0.8939, 0.1981, 0.9568],
         [0.6660, 0.6682, 0.9867],
         ...,
         [0.8856, 0.1539, 0.7902],
         [0.0580, 0.9192, 0.0741],
         [0.5635, 0.1261, 0.1200]],

        [[0.2404, 0.5772, 0.8935],
         [0.3540, 0.1140, 0.0716],
         [0.

### Zeros and Ones

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
# Use torch.range() and get deprecated message, use torch.arange()
torch.range(0,10)

C:\Users\rishav\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
one_to_ten = torch.arange(0,11)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
torch.arange(start=0,end=1000,step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [28]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes are one of the 3 big errors you'll run into with PyTorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing = https://en.wikipedia.org/wiki/Precision_(computer_science)

In [29]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                                dtype=None, # what datatype is the tensor (e.g. float32, float16, etc)
                                device=None, # what device is your tensor on
                                requires_grad=False) # whether or not to track gradients with this tensor operations

float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [33]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensors (Tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [34]:
# Create a tensor

some_tensor = torch.rand(3,2)
some_tensor

tensor([[0.3348, 0.7239],
        [0.7176, 0.2163],
        [0.0971, 0.4798]])

In [35]:
# Find out details from some_tensor

print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.3348, 0.7239],
        [0.7176, 0.2163],
        [0.0971, 0.4798]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 2])
Device of tensor: cpu


In [36]:
some_tensor.to(device='cuda')

tensor([[0.3348, 0.7239],
        [0.7176, 0.2163],
        [0.0971, 0.4798]], device='cuda:0')

### Manipulating Tensors (Tensor Operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [37]:
# Create a tensor and add 10 
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [38]:
# Multiply tensor by 10
tensor *10

tensor([10, 20, 30])

In [39]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [40]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [41]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multipiction in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimension**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [42]:
torch.matmul(torch.rand(3,3), torch.rand(3,2))

tensor([[0.0669, 0.5085],
        [0.1874, 0.7113],
        [0.3903, 1.3597]])

In [43]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f"Equals {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals tensor([1, 4, 9])


In [44]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [45]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [46]:
%%time

value = 0
for i in range(len(tensor)):
    value+=tensor[i] * tensor[i]
value

Wall time: 30.5 ms


tensor(14)

In [47]:
%%time

torch.matmul(tensor,tensor)

Wall time: 0 ns


tensor(14)

### One of the most common errors in deep learning: shape errors

In [48]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for matmul)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [49]:
tensor_B.T.shape

torch.Size([2, 3])

In [50]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <--inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <--inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, mean, max, sum, etc (tensor aggregation)

In [51]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
# Find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [53]:
# Find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [54]:
# Find the mean
torch.mean(x)

RuntimeError: Can only calculate the mean of floating types. Got Long instead.

In [55]:
x.dtype

torch.int64

In [56]:
# note: The torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [57]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [58]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [59]:
# Find the positions in tensor that has the minimum value with argmin() -> returns index position of target tensor wh
# where minimum value occurs

x.argmin()

tensor(0)

In [60]:
# Find the positions in tensor that has the minimum value with argmax() -> returns index position of target tensor wh
# where maximum value occurs
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [61]:
# Lets create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [62]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [63]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [64]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
# Changing z changes x as the view of a tensor shares the same memory as the original tensor
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [66]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1) 
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [67]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [68]:
# torch.unsqueeze() - adds a single dimensions to a target tensor at a specific dim (dimension)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [69]:
# torch.permute - rearranges the dimensions of a target tensor in a specific order
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

# Permuted tensor is a view of the original tensor

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

In [70]:
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [71]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [72]:
x[0][0]

tensor([1, 2, 3])

In [73]:
x[0][0][0]

tensor(1)

In [74]:
# You can aso use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [75]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [76]:
# Get all values of 0th but only the 1 index value 1st dimensions and 2nd dimension
x[:,1,1]

tensor([5])

In [77]:
# Get index 0 of 0th and 1st dimensions and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [78]:
# Index on x to return 9
x[:,2,2]

tensor([9])

In [79]:
# Index on x to return 3, 6, 9
x[0,:,2]

tensor([3, 6, 9])

### PyTorch tensors & NumPy

NumPy is a popular scientific Pythonnumeical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [1]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) # when converting from numpy -> pytorch, pytorch reflects numpy's default datatype 
                                            # float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [2]:
array.dtype

dtype('float64')

In [3]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [4]:
# Change the value of array, what will this do to `tensor`?
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [5]:
# Tensor to PyTorch
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [6]:
numpy_tensor.dtype

dtype('float32')

In [7]:
# Change the value of tensor, what will this do to `array`?
tensor = tensor+1
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

### Reproducibility (trying to take random out of random)

In short how a Neural Network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representatins of the data -> again -> again...`

To reduce randomness in neural networks and PyTorch comes the concept of a **random seed**.
Essentially what the random seed does is "flavour" the randomness.

In [8]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.6971, 0.1844, 0.2755, 0.3471],
        [0.1748, 0.3011, 0.1014, 0.5058],
        [0.4266, 0.5312, 0.9296, 0.3812]])
tensor([[0.6474, 0.9891, 0.9076, 0.4945],
        [0.0114, 0.7272, 0.7064, 0.2890],
        [0.6351, 0.1455, 0.2270, 0.3360]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [9]:
# Lets make some random but reproducible tensors

# set random seed
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.5349, 0.1988, 0.6592, 0.6569],
        [0.2328, 0.4251, 0.2071, 0.6297],
        [0.3653, 0.8513, 0.8549, 0.5509]])
tensor([[0.5349, 0.1988, 0.6592, 0.6569],
        [0.2328, 0.4251, 0.2071, 0.6297],
        [0.3653, 0.8513, 0.8549, 0.5509]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

### Running tensors and PyTorch objects on the GPUs (and making faster computation)



In [10]:
!nvidia-smi

Wed Jan 11 18:22:26 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 516.94       Driver Version: 516.94       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:06:00.0  On |                  N/A |
| 25%   33C    P8    N/A /  75W |    254MiB /  4096MiB |     12%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [11]:
# Check for GPU access with PyTorch

torch.cuda.is_available()

True

In [12]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [13]:
# Count number of devices
torch.cuda.device_count()

1

### Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [14]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3], device="cpu")

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [15]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU

In [16]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [17]:
# To fix the GPU tensor with NumPy issue we can first set it to the CPU
tensor_back_on_CPU = tensor_on_gpu.cpu().numpy()
tensor_back_on_CPU

array([1, 2, 3], dtype=int64)